version: '3.8'
services:
  app:
    container_name: nodejs-app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
    command: node index.js

volumes:
  node_data: 