apiVersion: apps/v1

kind: Deployment

metadata:

  name: nodejsapp

spec:

  selector:

    matchLabels:

      run: nodejsapp

  replicas: 3

  template:

    metadata:

      labels:

        run: nodejsapp


    spec:

      containers:

      - name: nodejsapp

        image: prasurani1/nodejsapp

        ports:

        - containerPort: 80

        resources:

          limits:

            cpu: 500m

          requests:

            cpu: 200m

