apiVersion: v1

kind: Service
metadata:
  name: nodejsapp
 # namespace: httpd-namespace-nautilus
spec:
  type: NodePort
  selector:
    app: nodejsapp
  ports:
    - port: 4000
      targetPort: 4000
      nodePort: 30005
