# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
#test1
name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  
  Run-npm-on-Ubuntu:
    name: Run npm on Ubuntu

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build
      #working-directory: 
      run: |
          npm install
          npm run build --if-present
          

  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        
        
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}  #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     # 
          SONAR_TOKEN:  ${{ secrets.SONAR_TOKEN }}     #530a47e41bd3d7dfef288890cb603c4a8a4a9863     #${{ secrets.SONAR_TOKEN }}
        with:
          sonar.projectKey: prasurani
          sonar.organisation: prasurani
        
        
 
 
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: prasurani1/nodejsapp1.1:v1.1
          
  
         
