# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
#test1
name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  
  Run-npm-on-Ubuntu:
    name: Run npm on Ubuntu

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build and test app
      working-directory: /home/runner/work/_temp/3d61d92c-75c6-4f9b-ba1e-768d92e5810e/nodejsapp
      run: |
          npm install
          npm run build --if-present
